language: node_js
node_js:
  - lts/carbon
cache:
  directories:
    - node_modules
before_install:
  - npm install -g npm@latest
install:
  - npm ci
  - npm install --no-save codecov
script:
  - jest --ci --coverage
after_success:
  - codecov
